[project]
name = "mcp-agent"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.9.0",
    "langchain-groq>=0.3.6",
    "langgraph>=0.5.3",
    "python-dotenv>=1.1.1",
    "torch>=2.7.1",
    "transformers>=4.53.2",
]
